# Partimos de una imagen base de ubuntudonde instalaremos apache, lo configuraremos y arrancaremos.
FROM ubuntu
ARG USUARIO
ARG PASSWORD
# ------Instalaciones------
RUN apt update && apt install -yq --no-install-recommends \
    apache2 \
    libapache2-mod-php7.2 \
    nano \
    curl \
    net-tools iputilils-ping
# ------Creacion de usuarios------
# Comandos interactivos (piden datos por terminal)
# Comandos por lotes (Datos los ponemos como parametros del comando)
RUN useradd -rm -d /home/${USUARIO} -s /bin/bash ${USUARIO}
RUN echo "${USUARIO}:~${PASSWORD}" | chpasswd
RUN echo "Bienvenido ${USUARIO}" > /home/${USUARIO}/hello.txt

    # Debemos consultar el docker hub de ese contenedor/imagen para ver variables de entorno,
# directorio de trabajo, etc.
# Directorio de trabajo dentro del contenedor.
WORKDIR /usr/www/html
COPY ../src .
EXPOSE 80
CMD apacchectl -DFOREGROUND